import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useSession } from 'next-auth/react';
import Session from 'components/Session';

function HomePage() {
  const router = useRouter();
  const { data: currentUser, status } = useSession();

  return (
    <>
      <Head>
        <title>Hello world.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="max-w-prose mx-auto">
          <h1 className="">Welcome</h1>
          <Session />
        </div>
      </main>
    </>
  );
}

export default HomePage;
